# Generated by Django 4.2.5 on 2023-09-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_alter_cars_image_2_alter_cars_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='fuel',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
