# Generated by Django 4.2.5 on 2023-10-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_cars_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='rental_places',
            field=models.ManyToManyField(to='adminside.rentalplace'),
        ),
    ]
