# Generated by Django 4.2.5 on 2023-10-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_rentalplace_cars_rental_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='rental_places',
        ),
        migrations.AddField(
            model_name='cars',
            name='rental_place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='RentalPlace',
        ),
    ]
