# Generated by Django 4.2.5 on 2023-10-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_coupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupon',
            new_name='Coupons',
        ),
    ]
