# Generated by Django 4.2.5 on 2023-10-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_rename_coupon_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='image_1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
