# Generated by Django 4.2.5 on 2023-10-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_coupons_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='uses_remaining',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
