# Generated by Django 4.2.5 on 2023-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
