# Generated by Django 4.2.4 on 2023-09-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_alter_user_managers_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
