# Generated by Django 4.2.4 on 2023-09-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0006_user_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street_address',
        ),
        migrations.AddField(
            model_name='user',
            name='licenseBack',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='licenseFront',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
