# Generated by Django 4.2.4 on 2023-09-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0007_remove_user_city_remove_user_pin_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='livePhoto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
