# Generated by Django 4.2.5 on 2023-10-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0009_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name1', models.CharField(max_length=200)),
            ],
        ),
    ]
