# Generated by Django 4.2.5 on 2023-10-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0010_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
