# Generated by Django 4.2.5 on 2023-11-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0011_delete_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
